### ISSUE TITLE
Lost ability to use text mode editing

### ISSUE THREAD

**Issue by RolfKyburz** [mibuthu/wp-event-list#154]
A really sad story: here's the plugin that worked OK for years, did (pretty much) exactly what I needed (not a calendar type function, but a list of upcoming events, with title, venue, date/time, category, description, featured image, and at the same time an archive of past events, which one can browse by year and category) — and for the past 2 years, there hasn't been any support to speak of. Not only does the plugin not support the block editor, but bugs are barely fixed, and apart from vague indications that he might re-tackle the plugin some day, the author appears to have vaporized.

While improvements (block editor) would have been really nice to have, the situation remained more or less workable for the past 2 - 3 years. However, for no apparent reason, I now can no longer switch to text mode editing. The latter to me is a must-have. At first, I thought that flaw is linked to a switch from PHP 7.2 to 7.4, but reverting to 7.2 does not fix the problem (the "<> Source Code" option in the classic editor menu isn't really helpful).

It looks as though sadly I must face reality and switch to a different plugin. The problem with this: I don't see a plugin alternative that is offering the same capabilities (suggestions anybody?), and even if an alternative existed, how do I go about exporting my entire event archive, and re-importing it into a new plugin???

**Comment by mibuthu** [comment]
I released an updated yesterday.

**Comment by RolfKyburz** [comment]
Nice try, and thanks for returning to the plugin! Sadly, I still cannot switch to text mode editing. The code option from the (classic) editor menu is hardly usable, as it shows all code without linefeeds, which makes it hardly readable. I'm not a developer — is it hard or impossible to enable the block editor in this plugin? this would allow me to switch to text mode editing on a per-block basis.

**Comment by RolfKyburz** [comment]
Thanks for looking into this, Michael!

**Comment by mibuthu** [comment]
I do not have the problem with the classic editor, but I will have a look at it later.

Of course it would be great to switch to the new editor, at least as an option. I have to check how difficult that is.

**Comment by RolfKyburz** [comment]
Of course, it's always possible that there is a conflict with another plugin, but as I haven't recently installed new plugins in that area, I did not suspect issues. Possible candidates: "TinyMCE Custom Styles", "Stylist", "Advanced TinyMCE Configuration", "Advanced Editor Tools (previously TinyMCE Advanced)" — though I don't see _any_ plausible reason why _any_ of these should interfere with text mode editing. I'm now on WP 5.5.3 and PHP 7.4.11

**Comment by mibuthu** [comment]
The combination with "TinyMCE Custom Styles" and "Advanced Editor Tools (previously TinyMCE Advanced)" seems to cause this issue.

**Comment by RolfKyburz** [comment]
Hmmm ... I have now deactivated "TinyMCE Custom Styles", "Advanced TinyMCE Configuration", "Advanced Editor Tools (previously TinyMCE Advanced)" — the issue persists, also if in addition I deactivate "Stylist". However, if you can make it fail with some of these plugins, this is at least a strong indication for a plugin conflict. As I don't have a site for testing and don't want to break my live site, I will probably keep the above plugins deactivated (especially as "Event List" is the only place where I still use the classic editor, hence the only reason to keep those plugins around), and perhaps—time permitting—try deactivating one or the other of the remaining plugins, where they seem non-essential. Also, so far, I have just deactivated, not deleted. If I don't miss any functionality, I will try eliminating the deactivated plugins, to see whether that maybe makes a difference? I'll keep you posted if I see any progress. And maybe there is a chance to see the block editor come alive in Events List??? Thanks again for helping!

**Comment by RolfKyburz** [comment]
I have in addition deactivated "Simple Image Sizes" and "Default Image Link"—to no avail. I have a sneaky suspicion that Yoast SEO (Premium) ius causing the conflict (too) — if so, there is no chance for me to test Event list without that — I cannot run my site without SEO in place. I have recently upgraded Yoast SEO to Premium. The Event List failure pre-dates that upgrade, but Yoast are doing frequent updates to their package all the time.
The most likely scenario for me—now that you have returned to working on the plugin—is to keep limping along, with the hope that the block editor will at some point become available. Should there be an error log for Event List editing?

**Comment by RolfKyburz** [comment]
Nope — Yoast SEO is not the culprit — temporary deactivation does not help.

**Comment by RolfKyburz** [comment]
Ah — found the (one of several?) culprit: after removing the "Amazon Associates Link Builder" plugin, the text mode works fine again. It's strange, since I have had that amazon plugin installed for at least 2 years, I suspect—and I don't see any updates to that plugin in my log. However, I note that the plugin is no longer on offer, so probably has been discontinued (in favor of several newer plugins).
I suspect that what happened is that a PHP or a WP update has introduced or revealed a conflict with that plugin. That plugin is not essential to me, so I have now permanently deleted it, along with "TinyMCE Custom Styles", "Advanced TinyMCE Configuration", "Simple Image Sizes", "Default Image Link", and "Stylist". The last one is non-essential, the other ones make sense only with the classic editor.
With this, I'm closing the issue now. Many thanks a lot for looking into this, for investigating & helping! Best wishes (still hoping to see the block editor in use for the Events List some day!).
-Rolf

**Comment by mibuthu** [comment]
I think we can keep this open, as it seems to be a problem with event-list that it conflicts with so many other plugins.

**Comment by mibuthu** [comment]
I did not found a conflict anymore. I only found a plugin which causes this issue also in the classic editor for posts and pages.
